-- Update initiative owners from final master table.

UPDATE "Initiative" SET "owner" = 'J. Matějček' WHERE "code" = 'ID001';
UPDATE "Initiative" SET "owner" = 'M. Zahradka; L. Plisz' WHERE "code" = 'ID005';
UPDATE "Initiative" SET "owner" = 'J. Novotny' WHERE "code" = 'ID006';
UPDATE "Initiative" SET "owner" = 'P. Kulišek; E. Zeman' WHERE "code" = 'ID007';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID008';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID009';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID010';
UPDATE "Initiative" SET "owner" = 'V. Ostin; VAQ' WHERE "code" = 'ID013';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID014';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID015';
UPDATE "Initiative" SET "owner" = 'A. Kadlecová' WHERE "code" = 'ID016';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID020';
UPDATE "Initiative" SET "owner" = 'R. Rajtar' WHERE "code" = 'ID023';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID024';
UPDATE "Initiative" SET "owner" = 'O. Koldinsky' WHERE "code" = 'ID026';
UPDATE "Initiative" SET "owner" = 'P. Petrýdes' WHERE "code" = 'ID027';
UPDATE "Initiative" SET "owner" = 'M. Dobrovsky' WHERE "code" = 'ID028';
UPDATE "Initiative" SET "owner" = 'M. Dobrovsky' WHERE "code" = 'ID029';
UPDATE "Initiative" SET "owner" = 'O. Koldinsky' WHERE "code" = 'ID031';
UPDATE "Initiative" SET "owner" = 'J. Havlas' WHERE "code" = 'ID032';
UPDATE "Initiative" SET "owner" = 'M. Dobrovsky; P. Kabelka' WHERE "code" = 'ID034';
UPDATE "Initiative" SET "owner" = 'P. Gudeljová' WHERE "code" = 'ID042';
UPDATE "Initiative" SET "owner" = 'J. Novotný; VE6' WHERE "code" = 'ID046';
UPDATE "Initiative" SET "owner" = 'Ch. Esser; O. Švásta' WHERE "code" = 'ID051';
UPDATE "Initiative" SET "owner" = 'J. Holubec' WHERE "code" = 'ID054';
UPDATE "Initiative" SET "owner" = 'L. Piesche; R. Hrdina' WHERE "code" = 'ID056';
UPDATE "Initiative" SET "owner" = 'O. Těšínský' WHERE "code" = 'ID058';
UPDATE "Initiative" SET "owner" = 'M. Fiedler; P. Halasniková' WHERE "code" = 'ID059';
UPDATE "Initiative" SET "owner" = 'L. Synáková' WHERE "code" = 'ID060';
UPDATE "Initiative" SET "owner" = 'P. Kabelka' WHERE "code" = 'ID061';
UPDATE "Initiative" SET "owner" = 'M. Lansdorf' WHERE "code" = 'ID062';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID063';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID072';
UPDATE "Initiative" SET "owner" = 'L. Petrbokova' WHERE "code" = 'ID074';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID076';
UPDATE "Initiative" SET "owner" = 'M. Mara' WHERE "code" = 'ID077';
UPDATE "Initiative" SET "owner" = 'J. Petrzelkova' WHERE "code" = 'ID078';
UPDATE "Initiative" SET "owner" = 'M. Kamarašová' WHERE "code" = 'ID079';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID081';
UPDATE "Initiative" SET "owner" = 'V. Mareckova' WHERE "code" = 'ID082';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID085';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID088';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID089';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID090';
UPDATE "Initiative" SET "owner" = 'P. Struzsky' WHERE "code" = 'ID092';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID099';
UPDATE "Initiative" SET "owner" = 'P. Kabelka' WHERE "code" = 'ID104';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID108';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID109';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID110';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID111';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID112';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID113';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID114';
UPDATE "Initiative" SET "owner" = 'M. Balon; K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID115';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID116';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID117';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID118';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID119';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID120';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID121';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID122';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID123';
UPDATE "Initiative" SET "owner" = 'K. Sklenar; P. Hospodar; L. Kaslova; T. Vit; P. Janeba' WHERE "code" = 'ID124';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID125';
UPDATE "Initiative" SET "owner" = 'J. Novotný; VE6' WHERE "code" = 'ID142';
UPDATE "Initiative" SET "owner" = 'Ch. Esser; J. Michal; J. Drescher' WHERE "code" = 'ID144';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID149';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID150';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID171';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID173';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID175';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID176';
UPDATE "Initiative" SET "owner" = 'J. Holubec' WHERE "code" = 'ID177';
UPDATE "Initiative" SET "owner" = 'J. Charvát' WHERE "code" = 'ID178';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID179';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID180';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID181';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID182';
UPDATE "Initiative" SET "owner" = 'O. Tichý' WHERE "code" = 'ID183';
UPDATE "Initiative" SET "owner" = 'M. Lansdorf' WHERE "code" = 'ID184';
UPDATE "Initiative" SET "owner" = 'L. Petrbokova' WHERE "code" = 'ID185';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID186';
UPDATE "Initiative" SET "owner" = 'J. Novotný; J. Michal' WHERE "code" = 'ID187';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID188';
UPDATE "Initiative" SET "owner" = 'D. Holub' WHERE "code" = 'ID189';
UPDATE "Initiative" SET "owner" = 'D. Holub' WHERE "code" = 'ID190';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID157';
UPDATE "Initiative" SET "owner" = 'J. Novotny' WHERE "code" = 'ID002';
UPDATE "Initiative" SET "owner" = 'L. Plisz' WHERE "code" = 'ID003';
UPDATE "Initiative" SET "owner" = 'D. Plath' WHERE "code" = 'ID011';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID017';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID018';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID019';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID049';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID050';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID134';
UPDATE "Initiative" SET "owner" = 'M. Zahradka' WHERE "code" = 'ID135';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID136';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID137';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID138';
UPDATE "Initiative" SET "owner" = 'K. Putnar' WHERE "code" = 'ID139';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID140';
UPDATE "Initiative" SET "owner" = 'J. Alaxin' WHERE "code" = 'ID158';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID162';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID163';
UPDATE "Initiative" SET "owner" = 'E. Werner / P. Retamozová' WHERE "code" = 'ID021';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID022';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID025';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID030';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID033';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID036';
UPDATE "Initiative" SET "owner" = 'V. Ostin' WHERE "code" = 'ID037';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID038';
UPDATE "Initiative" SET "owner" = 'O. Koldinsky' WHERE "code" = 'ID039';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID040';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID041';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID043';
UPDATE "Initiative" SET "owner" = 'P. Kabelka' WHERE "code" = 'ID044';
UPDATE "Initiative" SET "owner" = 'P. Sumovsky' WHERE "code" = 'ID045';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID047';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID048';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID141';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID159';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID164';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID165';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID166';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID143';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID145';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID04';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID052';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID053';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID055';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID065';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID066';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID067';
UPDATE "Initiative" SET "owner" = 'J. Soudek' WHERE "code" = 'ID068';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID069';
UPDATE "Initiative" SET "owner" = 'L. Petrbokova / M. Nazareth' WHERE "code" = 'ID070';
UPDATE "Initiative" SET "owner" = 'L. Petrbokova / M. Nazareth' WHERE "code" = 'ID071';
UPDATE "Initiative" SET "owner" = 'M. Mara' WHERE "code" = 'ID073';
UPDATE "Initiative" SET "owner" = 'M. Mara' WHERE "code" = 'ID075';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID174';
UPDATE "Initiative" SET "owner" = 'K. Putnar / T. Geist' WHERE "code" = 'ID012';
UPDATE "Initiative" SET "owner" = 'K. Putnar / T. Geist' WHERE "code" = 'ID035';
UPDATE "Initiative" SET "owner" = 'V. Calda' WHERE "code" = 'ID080';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID083';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID084';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID086';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID087';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID091';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID093';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID146';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID147';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID148';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID160';
UPDATE "Initiative" SET "owner" = 'T. Geist' WHERE "code" = 'ID167';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID168';
UPDATE "Initiative" SET "owner" = 'J. Petrzelkova' WHERE "code" = 'ID169';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID170';
UPDATE "Initiative" SET "owner" = 'T. Krap' WHERE "code" = 'ID172';
UPDATE "Initiative" SET "owner" = 'P. Jira' WHERE "code" = 'ID094';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID095';
UPDATE "Initiative" SET "owner" = 'P. Kabelka' WHERE "code" = 'ID096';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID097';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID098';
UPDATE "Initiative" SET "owner" = 'P. Kabelka' WHERE "code" = 'ID100';
UPDATE "Initiative" SET "owner" = 'C. Wong' WHERE "code" = 'ID101';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID102';
UPDATE "Initiative" SET "owner" = 'C. Wong' WHERE "code" = 'ID103';
UPDATE "Initiative" SET "owner" = 'V. Horakova, P. Kabelka' WHERE "code" = 'ID105';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID106';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID107';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID151';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID152';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID153';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID154';
UPDATE "Initiative" SET "owner" = 'V. Horakova' WHERE "code" = 'ID155';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID156';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID161';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID064';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID203';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID204';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID205';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID206';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID207';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID208';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID209';
UPDATE "Initiative" SET "owner" = 'TBD' WHERE "code" = 'ID210';