"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {Pencil} from "lucide-react";
import {updateInitiative} from "@/lib/actions/initiatives";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";

type Initiative={id:string;code:string|null;name:string;description:string;owner:string;stage:string;status:"ON_TRACK"|"AT_RISK"|"CRITICAL";startDate:string|null;targetDate:string|null};
export function EditInitiativeButton({initiative}:{initiative:Initiative}){const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const router=useRouter();async function submit(formData:FormData){setSaving(true);setError("");try{await updateInitiative(initiative.id,{code:String(formData.get("code")||""),name:String(formData.get("name")||""),description:String(formData.get("description")||""),owner:String(formData.get("owner")||""),stage:String(formData.get("stage")||"IDEATION") as any,status:initiative.status,startDate:String(formData.get("startDate")||""),targetDate:String(formData.get("targetDate")||"")});setOpen(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not update initiative.")}finally{setSaving(false)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline"><Pencil className="mr-1 h-4 w-4"/>Edit</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Edit Initiative</DialogTitle></DialogHeader><form action={submit} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">ID / Code<Input name="code" defaultValue={initiative.code??""} placeholder="Optional"/></label><label className="text-sm font-medium">Owner<Input name="owner" defaultValue={initiative.owner} required/></label></div><label className="text-sm font-medium">Name<Input name="name" defaultValue={initiative.name} required/></label><label className="text-sm font-medium">Description<Textarea name="description" defaultValue={initiative.description} required/></label><label className="text-sm font-medium">Stage<select name="stage" defaultValue={initiative.stage} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm">{["IDEATION","EVALUATION","DETAILING","DEVELOPMENT","ROLLOUT"].map(x=><option key={x} value={x}>{x[0]+x.slice(1).toLowerCase()}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Start Date<Input name="startDate" type="date" defaultValue={initiative.startDate??""}/></label><label className="text-sm font-medium">Target Date<Input name="targetDate" type="date" defaultValue={initiative.targetDate??""}/></label></div>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} className="bg-[#0E3A2F] text-white hover:bg-[#0E3A2F]/90">{saving?"Saving…":"Save Changes"}</Button></div></form></DialogContent></Dialog>}