"use client";
import { useState } from "react";
import { Mail,Phone,Pencil,Plus,UserMinus } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { createInitiativeContact,assignExistingContactToInitiative,removeInitiativeContact,updateContact } from "@/lib/actions/contacts";

type Item={id:string;name:string;role:string|null;email:string|null;phone:string|null};
type Option={id:string;name:string;role:string|null;email:string|null};
export function InitiativeContacts({initiativeId,contacts,allContacts=[]}:{initiativeId:string;contacts:Item[];allContacts?:Option[]}){
 const router=useRouter();const[selected,setSelected]=useState<Item|null>(null);const[adding,setAdding]=useState(false);const[saving,setSaving]=useState(false);const available=allContacts.filter(o=>!contacts.some(c=>c.id===o.id));
 async function save(fd:FormData){if(!selected)return;setSaving(true);try{await updateContact(selected.id,{name:String(fd.get("name")||""),role:String(fd.get("role")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||"")});setSelected(null);router.refresh()}finally{setSaving(false)}}
 async function create(fd:FormData){setSaving(true);try{await createInitiativeContact(initiativeId,{name:String(fd.get("name")||""),role:String(fd.get("role")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||"")});setAdding(false);router.refresh()}finally{setSaving(false)}}
 async function assign(id:string){setSaving(true);try{await assignExistingContactToInitiative(initiativeId,id);setAdding(false);router.refresh()}finally{setSaving(false)}}
 async function remove(){if(!selected)return;setSaving(true);try{await removeInitiativeContact(initiativeId,selected.id);setSelected(null);router.refresh()}finally{setSaving(false)}}
 return <><div className="mb-3 flex justify-end"><Button size="sm" onClick={()=>setAdding(true)}><Plus className="h-4 w-4"/>Add Contact</Button></div>{contacts.length?<div className="space-y-2">{contacts.map(c=><button key={c.id} onClick={()=>setSelected(c)} className="w-full rounded-lg border p-3 text-left hover:bg-muted/40"><div className="flex justify-between"><div><p className="text-sm font-medium">{c.name}</p>{c.role?<p className="text-xs text-muted-foreground">{c.role}</p>:null}</div><Pencil className="h-4 w-4 text-muted-foreground"/></div>{c.email?<p className="mt-2 flex gap-1.5 text-xs text-[#0E3A2F]"><Mail className="h-3.5 w-3.5"/>{c.email}</p>:null}{c.phone?<p className="mt-1 flex gap-1.5 text-xs text-muted-foreground"><Phone className="h-3.5 w-3.5"/>{c.phone}</p>:null}</button>)}</div>:<p className="text-sm text-muted-foreground">No initiative contacts.</p>}
 <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Edit Initiative Contact</DialogTitle></DialogHeader>{selected?<form action={save} className="space-y-3"><Input name="name" defaultValue={selected.name} required/><Input name="role" placeholder="Role / Function" defaultValue={selected.role??""}/><Input name="email" type="email" placeholder="Email" defaultValue={selected.email??""}/><Input name="phone" type="tel" placeholder="Phone" defaultValue={selected.phone??""}/><div className="flex justify-between"><Button type="button" variant="outline" onClick={remove} disabled={saving}><UserMinus className="h-4 w-4"/>Remove</Button><Button disabled={saving}>Save changes</Button></div></form>:null}</DialogContent></Dialog>
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Add Initiative Contact</DialogTitle></DialogHeader>{available.length?<div className="space-y-2"><p className="text-xs font-medium">Assign existing contact</p>{available.map(c=><button key={c.id} type="button" onClick={()=>assign(c.id)} className="w-full rounded-md border p-2 text-left hover:bg-muted/40"><p className="text-sm font-medium">{c.name}</p><p className="text-xs text-muted-foreground">{c.role||c.email||"Existing contact"}</p></button>)}<div className="border-t"/></div>:null}<form action={create} className="space-y-3"><p className="text-xs font-medium">Create new contact</p><Input name="name" placeholder="Name" required/><Input name="role" placeholder="Role / Function"/><Input name="email" type="email" placeholder="Email"/><Input name="phone" type="tel" placeholder="Phone"/><div className="flex justify-end"><Button disabled={saving}>Create & assign</Button></div></form></DialogContent></Dialog></>
}
