"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {Pencil,Plus} from "lucide-react";
import {createMarket,updateMarket} from "@/lib/actions/markets";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
type Market={id:string;code:string;name:string;region:string;lead:string;owner:string|null};
export function MarketFormButton({market}:{market?:Market}){const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const router=useRouter();async function submit(fd:FormData){setSaving(true);setError("");const input={code:String(fd.get("code")||""),name:String(fd.get("name")||""),region:String(fd.get("region")||""),lead:String(fd.get("lead")||""),owner:(String(fd.get("owner")||"")||undefined) as "Anna"|"Maja"|undefined};try{market?await updateMarket(market.id,input):await createMarket(input);setOpen(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not save market.")}finally{setSaving(false)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{market?<Button type="button" variant="outline" size="sm" onClick={(e)=>e.stopPropagation()}><Pencil className="h-4 w-4"/>Edit</Button>:<Button className="bg-[#0E3A2F] text-white hover:bg-[#0E3A2F]/90"><Plus className="h-4 w-4"/>Add Market</Button>}</DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{market?"Edit Market":"Add Market"}</DialogTitle></DialogHeader><form action={submit} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Code<Input name="code" defaultValue={market?.code??""} placeholder="e.g. ES" required/></label><label className="text-sm font-medium">Region<Input name="region" defaultValue={market?.region??""} placeholder="e.g. Southern Europe" required/></label></div><label className="text-sm font-medium">Name<Input name="name" defaultValue={market?.name??""} placeholder="e.g. Spain" required/></label><label className="text-sm font-medium">Lead<Input name="lead" defaultValue={market?.lead??""} placeholder="Optional"/></label><label className="text-sm font-medium">Market Owner<select name="owner" defaultValue={market?.owner??""} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select owner</option><option value="Maja">Maja</option><option value="Anna">Anna</option></select></label>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} className="bg-[#0E3A2F] text-white hover:bg-[#0E3A2F]/90">{saving?"Saving...":market?"Save Changes":"Add Market"}</Button></div></form></DialogContent></Dialog>}