"use client";

import { useState } from "react";
import { Mail, Phone, Pencil, Plus, UserMinus } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { createMarketContact, assignExistingContactToMarket, removeMarketContact, updateContact } from "@/lib/actions/contacts";

export type NetworkContactItem = { id:string; name:string; role:string|null; email:string|null; phone:string|null; sources:string[] };
export type ContactOption = { id:string; name:string; role:string|null; email:string|null };

export function NetworkContacts({ contacts, marketId, allContacts=[], headerActionOnly=false, contentOnly=false }:{ contacts:NetworkContactItem[]; marketId:string; allContacts?:ContactOption[]; headerActionOnly?:boolean; contentOnly?:boolean }) {
  const router=useRouter(); const [selected,setSelected]=useState<NetworkContactItem|null>(null); const [adding,setAdding]=useState(false); const [saving,setSaving]=useState(false);
  const available=allContacts.filter(option=>!contacts.some(contact=>contact.id===option.id));

  async function save(formData:FormData){if(!selected)return;setSaving(true);try{await updateContact(selected.id,{name:String(formData.get("name")??""),role:String(formData.get("role")??""),email:String(formData.get("email")??""),phone:String(formData.get("phone")??"")});setSelected(null);router.refresh();}finally{setSaving(false)}}
  async function create(formData:FormData){setSaving(true);try{await createMarketContact(marketId,{name:String(formData.get("name")??""),role:String(formData.get("role")??""),email:String(formData.get("email")??""),phone:String(formData.get("phone")??"")});setAdding(false);router.refresh();}finally{setSaving(false)}}
  async function assign(contactId:string){setSaving(true);try{await assignExistingContactToMarket(marketId,contactId);setAdding(false);router.refresh();}finally{setSaving(false)}}
  async function remove(){if(!selected)return;setSaving(true);try{await removeMarketContact(marketId,selected.id);setSelected(null);router.refresh();}finally{setSaving(false)}}

  if(headerActionOnly)return <><Button type="button" size="sm" onClick={()=>setAdding(true)}><Plus className="mr-1 h-3.5 w-3.5"/>Add Contact</Button><Dialog open={adding} onOpenChange={setAdding}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Add Network Contact</DialogTitle></DialogHeader><form action={create} className="space-y-3"><Input name="name" placeholder="Name" required/><Input name="role" placeholder="Role / Function"/><Input name="email" type="email" placeholder="Email"/><Input name="phone" type="tel" placeholder="Phone"/><Button disabled={saving}>Create & assign</Button></form></DialogContent></Dialog></>;
  return <>{!contentOnly?<div className="mb-2 flex justify-end"><Button type="button" size="sm" onClick={()=>setAdding(true)}><Plus className="mr-1 h-3.5 w-3.5"/>Add Contact</Button></div>:null}
    {!contacts.length?<p className="text-sm text-muted-foreground">No network contact available.</p>:<div className="space-y-3">{contacts.map(contact=><button key={contact.id} type="button" onClick={()=>setSelected(contact)} className="w-full rounded-lg border p-3 text-left transition-colors hover:bg-muted/40"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{contact.name}</p>{contact.role?<p className="text-xs text-muted-foreground">{contact.role}</p>:null}</div><Pencil className="h-3.5 w-3.5 shrink-0 text-muted-foreground"/></div><div className="mt-2 flex flex-col gap-1">{contact.email?<span className="flex items-center gap-1.5 text-xs text-[#0E3A2F]"><Mail className="h-3.5 w-3.5"/>{contact.email}</span>:null}{contact.phone?<span className="flex items-center gap-1.5 text-xs text-muted-foreground"><Phone className="h-3.5 w-3.5"/>{contact.phone}</span>:null}</div><div className="mt-2 flex flex-wrap gap-1">{contact.sources.map(source=><span key={source} className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-medium text-muted-foreground">{source}</span>)}</div></button>)}</div>}
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Edit Network Contact</DialogTitle></DialogHeader>{selected?<form action={save} className="space-y-4"><div><label className="mb-1 block text-xs font-medium">Name</label><Input name="name" defaultValue={selected.name} required/></div><div><label className="mb-1 block text-xs font-medium">Role / Function</label><Input name="role" defaultValue={selected.role??""}/></div><div><label className="mb-1 block text-xs font-medium">Email</label><Input name="email" type="email" defaultValue={selected.email??""}/></div><div><label className="mb-1 block text-xs font-medium">Phone</label><Input name="phone" type="tel" defaultValue={selected.phone??""}/></div><p className="text-xs text-muted-foreground">Assigned via: {selected.sources.join(", ")}</p><div className="flex justify-between gap-2"><Button type="button" variant="outline" disabled={saving||!selected.sources.includes("Market")} onClick={remove}><UserMinus className="mr-1 h-3.5 w-3.5"/>Remove from Market</Button><div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setSelected(null)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></div></div></form>:null}</DialogContent></Dialog>
    <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Add Network Contact</DialogTitle></DialogHeader>{available.length?<div><p className="mb-2 text-xs font-medium">Assign existing contact</p><div className="max-h-36 space-y-2 overflow-y-auto">{available.map(contact=><button key={contact.id} type="button" disabled={saving} onClick={()=>assign(contact.id)} className="w-full rounded-md border p-2 text-left hover:bg-muted/40"><p className="text-sm font-medium">{contact.name}</p><p className="text-xs text-muted-foreground">{contact.role||contact.email||"Existing contact"}</p></button>)}</div><div className="my-4 border-t"/></div>:null}<form action={create} className="space-y-3"><p className="text-xs font-medium">Create new contact</p><Input name="name" placeholder="Name" required/><Input name="role" placeholder="Role / Function"/><Input name="email" type="email" placeholder="Email"/><Input name="phone" type="tel" placeholder="Phone"/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setAdding(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving...":"Create & assign"}</Button></div></form></DialogContent></Dialog>
  </>;
}
