import { FolderOpen, Layers3 } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/shared/page-header";
import { InitiativeInput } from "@/components/initiatives/initiative-input";
import { AddInitiativeButton } from "@/components/initiatives/add-initiative-button";
import { DocumentsList } from "@/components/shared/documents-list";
import { KpiCard } from "@/components/dashboard/kpi-card";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { InitiativesList } from "@/components/initiatives/initiatives-list";
export const dynamic="force-dynamic";export const revalidate=0;
const stageLabel:Record<string,string>={IDEATION:"Ideation",EVALUATION:"Evaluation",DETAILING:"Detailing",DEVELOPMENT:"Development",ROLLOUT:"Rollout"};
export default async function InitiativesPage(){const [initiatives,generalDocuments]=await Promise.all([prisma.initiative.findMany({orderBy:{name:"asc"},include:{markets:{include:{market:true}}}}),prisma.document.findMany({where:{category:"GENERAL"},orderBy:{createdAt:"desc"},select:{id:true,name:true,pathname:true,size:true,createdAt:true}})]);const initiativeOptions=initiatives.map(({id,code,name})=>({id,code:code??"",name}));return <div><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><PageHeader title="Initiatives" description="HQ steering from ideation through ready-for-market rollout."/><div className="flex items-center gap-2"><InitiativeInput initiatives={initiativeOptions}/><AddInitiativeButton/></div></div><div className="mb-6 grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,0.7fr)_minmax(0,1.3fr)]"><KpiCard label="Total initiatives" value={initiatives.length} icon={Layers3} hint="total initiative portfolio"/><Card className="border-[#78FAAE] bg-[#78FAAE]/5"><CardHeader className="flex flex-row items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#78FAAE] p-2 text-[#0D3B32]"><FolderOpen className="h-5 w-5"/></div><div><p className="text-base font-semibold">General</p><p className="text-sm text-muted-foreground">Project-wide inputs and source files that are not assigned to a specific initiative.</p></div></div><span className="shrink-0 rounded-full border border-[#78FAAE] bg-background px-2.5 py-1 text-xs font-medium text-[#0D3B32]">{generalDocuments.length} {generalDocuments.length===1?"document":"documents"}</span></CardHeader><CardContent>{generalDocuments.length>0?<DocumentsList documents={generalDocuments}/>:<p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No General inputs yet. Use the Input button above and select General to add project-wide information.</p>}</CardContent></Card></div><InitiativesList initiatives={initiatives.map(i=>({id:i.id,code:i.code,name:i.name,owner:i.owner,description:i.description,stage:i.stage,targetLabel:i.targetDate?`Target: ${i.targetDate.toLocaleString("en",{month:"short",year:"numeric"})}`:"Target: Not set",markets:i.markets.map(mi=>({id:mi.id,code:mi.market.code}))}))}/></div>}